# Generated by Django 2.0 on 2018-06-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=20, verbose_name='告警id')),
                ('trigger', models.CharField(max_length=50, verbose_name='触发器')),
                ('host', models.CharField(max_length=30, verbose_name='hostname')),
                ('datetime', models.DateField(verbose_name='日期')),
                ('message', models.CharField(max_length=60, verbose_name='消息')),
                ('status', models.CharField(choices=[('0', 'restored'), ('1', 'no-recovered')], max_length=1, verbose_name='告警状态')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(max_length=10, verbose_name='告警级别')),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=50, verbose_name='告警项')),
                ('level', models.CharField(max_length=10, verbose_name='告警登记')),
            ],
        ),
    ]
